toolbar:
  - insertfile undo redo | styleselect | outdent indent | link image | emoticons | forecolor backcolor | media | table
plugins:
  - link
  - uploadimage
  - textcolor
  - code
  - emoticons
  - table
  - media